# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 20:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shout', models.CharField(max_length=160)),
                ('user', models.CharField(max_length=150)),
                ('shout_at', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2016, 10, 30)),
        ),
    ]
