# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shout', '0002_auto_20161030_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shouts',
            name='shout_at',
            field=models.DateTimeField(max_length=50),
        ),
    ]
