# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shout', '0004_auto_20161110_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='invitees',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='event_descp',
            field=models.CharField(max_length=250),
        ),
    ]
